In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
# colums value
# UtilityBillsPaymentHistory removed
categorical_columns = [
    'EmploymentStatus',
    'EducationLevel',
    'MaritalStatus',
    'HomeOwnershipStatus',
    'BankruptcyHistory',
    'LoanPurpose',
    'PaymentHistory',
    'LoanApproved'
]

numeric_columns = [
    'Age',
    'AnnualIncome',
    'CreditScore',
    'Experience',
    'LoanAmount',
    'LoanDuration',
    'NumberOfDependents',
    'MonthlyDebtPayments',
    'CreditCardUtilizationRate',
    'NumberOfOpenCreditLines',
    'NumberOfCreditInquiries',
    'DebtToIncomeRatio',
    'PreviousLoanDefaults',
    'LengthOfCreditHistory',
    'SavingsAccountBalance',
    'CheckingAccountBalance',
    'TotalAssets',
    'TotalLiabilities',
    'MonthlyIncome',
    'JobTenure',
    'NetWorth',
    'BaseInterestRate',
    'InterestRate',
    'MonthlyLoanPayment',
    'TotalDebtToIncomeRatio',
    'RiskScore'
]

In [4]:
## Load Data
# Type your Loan.csv path
file_path = 'C:/Users/Allen/VSCpr/CS513FinalProject/data/Loan.csv'

# Loading Data
df = pd.read_csv(file_path)
print(df.describe())
df.head()

                Age   AnnualIncome   CreditScore    Experience     LoanAmount  \
count  20000.000000   20000.000000  20000.000000  20000.000000   20000.000000
mean      39.752600   59161.473550    571.612400     17.522750   24882.867800
std       11.622713   40350.845168     50.997358     11.316836   13427.421217
min       18.000000   15000.000000    343.000000      0.000000    3674.000000
25%       32.000000   31679.000000    540.000000      9.000000   15575.000000
50%       40.000000   48566.000000    578.000000     17.000000   21914.500000
75%       48.000000   74391.000000    609.000000     25.000000   30835.000000
max       80.000000  485341.000000    712.000000     61.000000  184732.000000

       LoanDuration  NumberOfDependents  MonthlyDebtPayments  \
count  20000.000000        20000.000000         20000.000000
mean      54.057000            1.517300           454.292700
std       24.664857            1.386325           240.507609
min       12.000000            0.000000            50.000000
25%       36.000000            0.000000           286.000000
50%       48.000000            1.000000           402.000000
75%       72.000000            2.000000           564.000000
max      120.000000            5.000000          2919.000000

       CreditCardUtilizationRate  NumberOfOpenCreditLines  ...  MonthlyIncome  \
count               20000.000000             20000.000000  ...   20000.000000
mean                    0.286381                 3.023350  ...    4891.715521
std                     0.159793                 1.736161  ...    3296.771598
min                     0.000974                 0.000000  ...    1250.000000
25%                     0.160794                 2.000000  ...    2629.583333
50%                     0.266673                 3.000000  ...    4034.750000
75%                     0.390634                 4.000000  ...    6163.000000
max                     0.917380                13.000000  ...   25000.000000

       UtilityBillsPaymentHistory     JobTenure      NetWorth  \
count                20000.000000  20000.000000  2.000000e+04
mean                     0.799918      5.002650  7.229432e+04
std                      0.120665      2.236804  1.179200e+05
min                      0.259203      0.000000  1.000000e+03
25%                      0.727379      3.000000  8.734750e+03
50%                      0.820962      5.000000  3.285550e+04
75%                      0.892333      6.000000  8.882550e+04
max                      0.999433     16.000000  2.603208e+06

       BaseInterestRate  InterestRate  MonthlyLoanPayment  \
count      20000.000000  20000.000000        20000.000000
mean           0.239124      0.239110          911.607052
std            0.035509      0.042205          674.583473
min            0.130101      0.113310           97.030193
25%            0.213889      0.209142          493.763700
50%            0.236157      0.235390          728.511452
75%            0.261533      0.265532         1112.770759
max            0.405029      0.446787        10892.629520

       TotalDebtToIncomeRatio  LoanApproved     RiskScore
count            20000.000000  20000.000000  20000.000000
mean                 0.402182      0.239000     50.766780
std                  0.338924      0.426483      7.778262
min                  0.016043      0.000000     28.800000
25%                  0.179693      0.000000     46.000000
50%                  0.302711      0.000000     52.000000
75%                  0.509214      0.000000     56.000000
max                  4.647657      1.000000     84.000000

[8 rows x 30 columns]

,ApplicationDate,Age,AnnualIncome,CreditScore,EmploymentStatus,EducationLevel,Experience,LoanAmount,LoanDuration,MaritalStatus,...,MonthlyIncome,UtilityBillsPaymentHistory,JobTenure,NetWorth,BaseInterestRate,InterestRate,MonthlyLoanPayment,TotalDebtToIncomeRatio,LoanApproved,RiskScore
0,2018-01-01,45,39948,617,Employed,Master,22,13152,48,Married,...,3329.000000,0.724972,11,126928,0.199652,0.227590,419.805992,0.181077,0,49.0
1,2018-01-02,38,39709,628,Employed,Associate,15,26045,48,Single,...,3309.083333,0.935132,3,43609,0.207045,0.201077,794.054238,0.389852,0,52.0
2,2018-01-03,47,40724,570,Employed,Bachelor,26,17627,36,Married,...,3393.666667,0.872241,6,5205,0.217627,0.212548,666.406688,0.462157,0,52.0
3,2018-01-04,58,69084,545,Employed,High School,34,37898,96,Single,...,5757.000000,0.896155,5,99452,0.300398,0.300911,1047.506980,0.313098,0,54.0
4,2018-01-05,37,103264,594,Employed,Associate,17,9184,36,Married,...,8605.333333,0.941369,5,227019,0.197184,0.175990,330.179140,0.070210,1,36.0

In [5]:
# Change column types where applicable
# UtilityBillsPaymentHistory removed
# Check and remove 'UtilityBillsPaymentHistory' column if it exists
if 'UtilityBillsPaymentHistory' in df.columns:
    df = df.drop('UtilityBillsPaymentHistory', axis=1)

for col in categorical_columns:
    df[col] = df[col].astype('category')

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Convert 'ApplicationDate' to datetime
df['ApplicationDate'] = pd.to_datetime(df['ApplicationDate'], errors='coerce')

# Compute the summary statistics for numeric columns
summary = df.head()

# Print the summary
print(summary)

print('\n min, max, mean only')
Min_Max_Mean=df.describe(include=[float, int]).loc[["min", "max", "mean"]]
print(Min_Max_Mean)

  ApplicationDate  Age  AnnualIncome  CreditScore EmploymentStatus  \
0      2018-01-01   45         39948          617         Employed
1      2018-01-02   38         39709          628         Employed
2      2018-01-03   47         40724          570         Employed
3      2018-01-04   58         69084          545         Employed
4      2018-01-05   37        103264          594         Employed

  EducationLevel  Experience  LoanAmount  LoanDuration MaritalStatus  ...  \
0         Master          22       13152            48       Married  ...
1      Associate          15       26045            48        Single  ...
2       Bachelor          26       17627            36       Married  ...
3    High School          34       37898            96        Single  ...
4      Associate          17        9184            36       Married  ...

   TotalLiabilities MonthlyIncome  JobTenure  NetWorth  BaseInterestRate  \
0             19183   3329.000000         11    126928          0.199652
1              9595   3309.083333          3     43609          0.207045
2            128874   3393.666667          6      5205          0.217627
3              5370   5757.000000          5     99452          0.300398
4             17286   8605.333333          5    227019          0.197184

   InterestRate  MonthlyLoanPayment TotalDebtToIncomeRatio LoanApproved  \
0      0.227590          419.805992               0.181077            0
1      0.201077          794.054238               0.389852            0
2      0.212548          666.406688               0.462157            0
3      0.300911         1047.506980               0.313098            0
4      0.175990          330.179140               0.070210            1

   RiskScore
0       49.0
1       52.0
2       52.0
3       54.0
4       36.0

[5 rows x 35 columns]

 min, max, mean only
          Age  AnnualIncome  CreditScore  Experience   LoanAmount  \
min   18.0000   15000.00000     343.0000     0.00000    3674.0000
max   80.0000  485341.00000     712.0000    61.00000  184732.0000
mean  39.7526   59161.47355     571.6124    17.52275   24882.8678

      LoanDuration  NumberOfDependents  MonthlyDebtPayments  \
min         12.000              0.0000              50.0000
max        120.000              5.0000            2919.0000
mean        54.057              1.5173             454.2927

      CreditCardUtilizationRate  NumberOfOpenCreditLines  ...   TotalAssets  \
min                    0.000974                  0.00000  ...  2.098000e+03
max                    0.917380                 13.00000  ...  2.619627e+06
mean                   0.286381                  3.02335  ...  9.696440e+04

      TotalLiabilities  MonthlyIncome  JobTenure      NetWorth  \
min       3.720000e+02    1250.000000    0.00000  1.000000e+03
max       1.417302e+06   25000.000000   16.00000  2.603208e+06
mean      3.625241e+04    4891.715521    5.00265  7.229432e+04

      BaseInterestRate  InterestRate  MonthlyLoanPayment  \
min           0.130101      0.113310           97.030193
max           0.405029      0.446787        10892.629520
mean          0.239124      0.239110          911.607052

      TotalDebtToIncomeRatio  RiskScore
min                 0.016043   28.80000
max                 4.647657   84.00000
mean                0.402182   50.76678

[3 rows x 26 columns]

In [6]:
print(df[df.isna().any(axis=1)]) # show the na in the data frame
missing_values =df.isnull().sum()
print(missing_values)

Empty DataFrame
Columns: [ApplicationDate, Age, AnnualIncome, CreditScore, EmploymentStatus, EducationLevel, Experience, LoanAmount, LoanDuration, MaritalStatus, NumberOfDependents, HomeOwnershipStatus, MonthlyDebtPayments, CreditCardUtilizationRate, NumberOfOpenCreditLines, NumberOfCreditInquiries, DebtToIncomeRatio, BankruptcyHistory, LoanPurpose, PreviousLoanDefaults, PaymentHistory, LengthOfCreditHistory, SavingsAccountBalance, CheckingAccountBalance, TotalAssets, TotalLiabilities, MonthlyIncome, JobTenure, NetWorth, BaseInterestRate, InterestRate, MonthlyLoanPayment, TotalDebtToIncomeRatio, LoanApproved, RiskScore]
Index: []

[0 rows x 35 columns]
ApplicationDate              0
Age                          0
AnnualIncome                 0
CreditScore                  0
EmploymentStatus             0
EducationLevel               0
Experience                   0
LoanAmount                   0
LoanDuration                 0
MaritalStatus                0
NumberOfDependents           0
HomeOwnershipStatus          0
MonthlyDebtPayments          0
CreditCardUtilizationRate    0
NumberOfOpenCreditLines      0
NumberOfCreditInquiries      0
DebtToIncomeRatio            0
BankruptcyHistory            0
LoanPurpose                  0
PreviousLoanDefaults         0
PaymentHistory               0
LengthOfCreditHistory        0
SavingsAccountBalance        0
CheckingAccountBalance       0
TotalAssets                  0
TotalLiabilities             0
MonthlyIncome                0
JobTenure                    0
NetWorth                     0
BaseInterestRate             0
InterestRate                 0
MonthlyLoanPayment           0
TotalDebtToIncomeRatio       0
LoanApproved                 0
RiskScore                    0
dtype: int64

In [11]:
# Target column is 'LoanApproved'
# One-Hot Encoding for categorical columns
attr = pd.get_dummies(df[categorical_columns + numeric_columns], drop_first=True)
  # Features (all columns except the target)
target = df['LoanApproved']  # Target variable

# Split data into training and testing sets
attr_train, attr_test, target_train, target_test = train_test_split(
    attr, target, test_size=0.25, random_state=44, shuffle=True
)

# Inspect the splits
print("Training Features Shape:", attr_train.shape)
print("Testing Features Shape:", attr_test.shape)
print("Training Target Shape:", target_train.shape)
print("Testing Target Shape:", target_test.shape)

# Optional: Display summaries
print("Training Data Summary:\n", attr_train.describe())
print("Testing Data Summary:\n", attr_test.describe())

Training Features Shape: (15000, 81)
Testing Features Shape: (5000, 81)
Training Target Shape: (15000,)
Testing Target Shape: (5000,)
Training Data Summary:
                 Age   AnnualIncome   CreditScore    Experience     LoanAmount  \
count  15000.000000   15000.000000  15000.000000  15000.000000   15000.000000
mean      39.773533   59164.987800    571.663200     17.539333   24970.851667
std       11.605942   40198.488484     50.801418     11.294832   13453.587720
min       18.000000   15000.000000    362.000000      0.000000    3729.000000
25%       32.000000   31737.250000    541.000000      9.000000   15684.500000
50%       40.000000   48707.500000    578.000000     17.000000   21958.000000
75%       48.000000   74251.250000    609.000000     25.000000   30868.000000
max       80.000000  485341.000000    712.000000     60.000000  184732.000000

       LoanDuration  NumberOfDependents  MonthlyDebtPayments  \
count  15000.000000        15000.000000         15000.000000
mean      53.977600            1.506867           455.457533
std       24.664048            1.382346           243.899906
min       12.000000            0.000000            73.000000
25%       36.000000            0.000000           285.000000
50%       48.000000            1.000000           401.000000
75%       72.000000            2.000000           567.000000
max      120.000000            5.000000          2919.000000

       CreditCardUtilizationRate  NumberOfOpenCreditLines  ...   TotalAssets  \
count               15000.000000             15000.000000  ...  1.500000e+04
mean                    0.286246                 3.033067  ...  9.713134e+04
std                     0.159640                 1.738172  ...  1.215273e+05
min                     0.002672                 0.000000  ...  2.098000e+03
25%                     0.160834                 2.000000  ...  3.131775e+04
50%                     0.266140                 3.000000  ...  6.106350e+04
75%                     0.391371                 4.000000  ...  1.172958e+05
max                     0.917380                13.000000  ...  2.619627e+06

       TotalLiabilities  MonthlyIncome     JobTenure      NetWorth  \
count      1.500000e+04   15000.000000  15000.000000  1.500000e+04
mean       3.653665e+04    4887.427822      5.008800  7.219131e+04
std        4.790111e+04    3268.698389      2.243002  1.185369e+05
min        3.720000e+02    1250.000000      0.000000  1.000000e+03
25%        1.119050e+04    2633.875000      3.000000  8.740000e+03
50%        2.234100e+04    4040.708333      5.000000  3.283900e+04
75%        4.339075e+04    6148.750000      6.000000  8.838900e+04
max        1.417302e+06   25000.000000     16.000000  2.603208e+06

       BaseInterestRate  InterestRate  MonthlyLoanPayment  \
count      15000.000000  15000.000000        15000.000000
mean           0.239121      0.239033          916.217206
std            0.035462      0.042207          678.030029
min            0.130101      0.113310           97.030193
25%            0.214056      0.209273          497.295771
50%            0.236293      0.235390          731.027587
75%            0.261510      0.265391         1116.049128
max            0.405029      0.429390        10892.629520

       TotalDebtToIncomeRatio     RiskScore
count            15000.000000  15000.000000
mean                 0.401997     50.777027
std                  0.335424      7.753323
min                  0.016043     28.800000
25%                  0.180451     46.000000
50%                  0.303436     52.000000
75%                  0.512430     56.000000
max                  4.647657     84.000000

[8 rows x 26 columns]
Testing Data Summary:
                Age   AnnualIncome  CreditScore   Experience     LoanAmount  \
count  5000.000000    5000.000000  5000.000000  5000.000000    5000.000000
mean     39.689800   59150.930800   571.460000    17.473000   24618.916200
std      11.673818   40808.551297    51.585531    11.383584   13346.473953
min      18.000000   15000.000000   343.000000     0.000000    3674.000000
25%      31.000000   31513.000000   540.000000     9.000000   15292.750000
50%      40.000000   48159.500000   579.000000    17.000000   21788.500000
75%      48.000000   74747.250000   609.000000    25.000000   30651.750000
max      80.000000  300000.000000   703.000000    61.000000  148776.000000

       LoanDuration  NumberOfDependents  MonthlyDebtPayments  \
count   5000.000000         5000.000000          5000.000000
mean      54.295200            1.548600           450.798200
std       24.668218            1.397866           230.019079
min       12.000000            0.000000            50.000000
25%       36.000000            0.000000           287.000000
50%       48.000000            1.000000           404.000000
75%       72.000000            3.000000           556.250000
max      120.000000            5.000000          2005.000000

       CreditCardUtilizationRate  NumberOfOpenCreditLines  ...   TotalAssets  \
count                5000.000000              5000.000000  ...  5.000000e+03
mean                    0.286787                 2.994200  ...  9.646355e+04
std                     0.160266                 1.729961  ...  1.186016e+05
min                     0.000974                 0.000000  ...  2.597000e+03
25%                     0.160706                 2.000000  ...  3.083425e+04
50%                     0.267582                 3.000000  ...  5.962050e+04
75%                     0.388191                 4.000000  ...  1.178805e+05
max                     0.878564                12.000000  ...  2.131807e+06

       TotalLiabilities  MonthlyIncome    JobTenure      NetWorth  \
count       5000.000000    5000.000000  5000.000000  5.000000e+03
mean       35399.704000    4904.578617     4.984200  7.260334e+04
std        45240.742275    3379.892256     2.218228  1.160608e+05
min          625.000000    1250.000000     0.000000  1.009000e+03
25%        11221.000000    2616.833333     3.000000  8.712500e+03
50%        21733.000000    3998.458333     5.000000  3.301900e+04
75%        42366.000000    6199.125000     6.000000  8.980500e+04
max       731375.000000   25000.000000    14.000000  2.106873e+06

       BaseInterestRate  InterestRate  MonthlyLoanPayment  \
count       5000.000000   5000.000000         5000.000000
mean           0.239135      0.239342          897.776589
std            0.035656      0.042204          664.011568
min            0.147615      0.125214          114.831862
25%            0.213383      0.208910          481.313922
50%            0.235818      0.235403          722.800618
75%            0.261598      0.265814         1103.022756
max            0.403615      0.446787         8754.455749

       TotalDebtToIncomeRatio    RiskScore
count             5000.000000  5000.000000
mean                 0.402737    50.736040
std                  0.349248     7.853305
min                  0.024642    28.800000
25%                  0.177327    46.000000
50%                  0.300093    52.000000
75%                  0.502530    56.000000
max                  4.143180    79.000000

[8 rows x 26 columns]

In [12]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
k_values = [3, 4,5,6, 10]

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors = k)
    knn.fit(attr_train, target_train)
    target_pred = knn.predict(attr_test)
#     accuracy = round(np.mean(target_test==target_pred ) * 100, 2)
    accuracy = accuracy_score(target_test,target_pred ) 
    print(f'Accuracy of model with k = {k}: {accuracy}%')
    print('')

C:\Users\Allen\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
found 0 physical cores < 1
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\Users\Allen\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\joblib\externals\loky\backend\context.py", line 282, in _count_physical_cores
    raise ValueError(f"found {cpu_count_physical} physical cores < 1")

Accuracy of model with k = 3: 0.8592%

Accuracy of model with k = 4: 0.8628%

Accuracy of model with k = 5: 0.867%

Accuracy of model with k = 6: 0.8644%

Accuracy of model with k = 10: 0.8706%